@BASE_URL = http://localhost:5000/api

### Test if express is working
GET http://localhost:5000/

### student/ Get all students
GET {{BASE_URL}}/student

### student/:id Get one student
GET {{BASE_URL}}/student/1591111934265

### Create a new student
POST {{BASE_URL}}/student
Content-Type: application/json

{ "firstname": "Noel", "lastname": "Ford", "dob": "2001-01-01", "email": "leon@example.com" }

### student/:id Delete a student
DELETE {{BASE_URL}}/student/1591126826350

### student/:id Update a student
PATCH {{BASE_URL}}/student/1591126826350
Content-Type: application/json

{ "firstname": "Leon" }